### ISSUE TITLE
Incompatible with latest version of Mapbox (3.5.2)

### ISSUE THREAD

**Issue by MetaHeavies** [nagix/mapbox-gl-rain-layer#22]
The example implementation works with mapbox 2.9.1 (using a CDN link)

However when using the latest build of mapbox 3.5.2 the following errors occur when trying to interact with the map:

 mapbox-gl-rain-layer.js?v=31fb7a9c:24904 Uncaught TypeError: callback is not a function
    at mapbox-gl-rain-layer.js?v=31fb7a9c:24904:5
    at kt.unloadTile (chunk-PLI7C4MI.js?v=31fb7a9c:20015:185)
    at kt.unloadTile (mapbox-gl-rain-layer.js?v=31fb7a9c:24882:41)
    at Xx._unloadTile (chunk-PLI7C4MI.js?v=31fb7a9c:13555:35)
    at Xx._removeTile (chunk-PLI7C4MI.js?v=31fb7a9c:13842:319)
    at Xx.update (chunk-PLI7C4MI.js?v=31fb7a9c:13757:162)
    at Ma.updateSources (chunk-PLI7C4MI.js?v=31fb7a9c:27422:44)
    at Map._render (chunk-PLI7C4MI.js?v=31fb7a9c:30237:187)
    at chunk-PLI7C4MI.js?v=31fb7a9c:30352:76
    

This seems to happen as soon as any user interaction with the map is taken, especially zoom (via scrollwheel, nav controls etc.)

Macbook M2
Chrome Version 126.0.6478.127
Vanilla JS

**Comment by nagix** [comment]
@MetaHeavies Thank you for reporting this! I have already identified the issue and will release a new version soon.

**Comment by nagix** [comment]
Fixed with fb7dd03. The version 0.6.0 will incorporate it.
